### ISSUE TITLE
Code-Related Benchmarks

### ISSUE THREAD

**Issue by john-b-yang** [tjunlp-lab/Awesome-LLMs-Evaluation-Papers#11]
Hi TJUNLP team, thanks so much for the great work! I think a paper that presents a holistic view of current NLP benchmarks is relevant amidst the many ongoing efforts.

To this end, I'd like to point out a couple works concerning evaluating language models on the coding related tasks, such as completion, patch generation, and language agents using code as actions.

- DS-1000: A Natural and Reliable Benchmark for Data Science Code Generation; [paper](https://arxiv.org/abs/2211.11501), [site](https://ds1000-code-gen.github.io/)
- SWE-bench: Can Language Models Resolve Real-World GitHub Issues?; [paper](https://arxiv.org/abs/2310.06770), [site](https://www.swebench.com/)
- InterCode: Standardizing and Benchmarking Interactive Coding with Execution Feedback; [paper](https://arxiv.org/abs/2306.14898), [site](https://intercode-benchmark.github.io/)

Thanks in advance!

**Comment by allen3ai** [comment]
We have added these paper into our paperlist and will update our survey including them in next version.

**Comment by john-b-yang** [comment]
Sweet, thanks so much for the update!
